item [
   id:1
   name:'empty date'

   id:2
   name:'date'
   
   id:3
   name:'empty invoice no.'

   id:4
   name:'invoice no.'

   id:5
   name:'empty quantity'
   
   id:6
   name:'quantity'
  
   id:7
   name:'empty item'
  
   id:8
   name:'item'
  
   id:9
   name:'empty price'
   
   id:10
   name:'empty total'

   id:11
   name:'empty amount'

   id:12
   name:'price'

   id:13
   name:'total'

   id:14
   name:'amount'

   id:15
   name:'bill to'

   id:16
   name:'person'
]          
